**Nível 1: Básico (URLs, Parâmetros e Cabeçalhos)**

In [22]:
import requests
import pandas as pd
import io
from bs4 import BeautifulSoup

url = "https://jsonplaceholder.typicode.com/posts"

params = {
    "userId": 2,
    "_limit": 5
}

resposta = requests.get(url, params=params, timeout=10)

print(resposta.status_code)
print(resposta.url)
print(resposta.json())

200
https://jsonplaceholder.typicode.com/posts?userId=2&_limit=5
[{'userId': 2, 'id': 11, 'title': 'et ea vero quia laudantium autem', 'body': 'delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi'}, {'userId': 2, 'id': 12, 'title': 'in quibusdam tempore odit est dolorem', 'body': 'itaque id aut magnam\npraesentium quia et ea odit et ea voluptas et\nsapiente quia nihil amet occaecati quia id voluptatem\nincidunt ea est distinctio odio'}, {'userId': 2, 'id': 13, 'title': 'dolorum ut in voluptas mollitia et saepe quo animi', 'body': 'aut dicta possimus sint mollitia voluptas commodi quo doloremque\niste corrupti reiciendis voluptatem eius rerum\nsit cumque quod eligendi laborum minima\nperferendis recusandae assumenda consectetur porro architecto ipsum ipsam'}, {'userId': 2, 'id': 14, 'title': 'voluptatem eligendi optio', 'body': 'fuga et accusamus dolorum perferendis illo voluptas\nnon doloremque neque facere\nad qui dolorum molestiae beatae\nsed aut voluptas totam sit illum'}, {'userId': 2, 'id': 15, 'title': 'eveniet quod temporibus', 'body': 'reprehenderit quos placeat\nvelit minima officia dolores impedit repudiandae molestiae nam\nvoluptas recusandae quis delectus\nofficiis harum fugiat vitae'}]

In [4]:
headers = {
    "User-Agent": "MeuProjetoPython/1.0"
}

resposta = requests.get(
    url,
    params=params,
    headers=headers,
    timeout=10
)

print(resposta.status_code)
print(resposta.url)

200
https://jsonplaceholder.typicode.com/posts?userId=2&_limit=5

**Nível 2: Intermediário (JSON, Erros e Arquivos Binários)**

In [12]:
ceps = [
    "24130001",
    "24130223",
    "24020125"
]

resultados = []

for cep in ceps:
    url = f"https://viacep.com.br/ws/{cep}/json/"

    resposta = requests.get(url, timeout=10)

    if resposta.status_code == 200:
        dados = resposta.json()
        resultados.append(dados)

df = pd.DataFrame(resultados)

df

,cep,logradouro,complemento,unidade,bairro,localidade,uf,estado,regiao,ibge,gia,ddd,siafi
0,24130-001,Alameda São Boaventura,de 441 a 819 - lado ímpar,,Fonseca,Niterói,RJ,Rio de Janeiro,Sudeste,3303302,,21,5865
1,24130-223,Alameda São Boaventura,de 821 ao fim - lado ímpar,,Fonseca,Niterói,RJ,Rio de Janeiro,Sudeste,3303302,,21,5865
2,24020-125,Rua Quinze de Novembro,,,Centro,Niterói,RJ,Rio de Janeiro,Sudeste,3303302,,21,5865

In [13]:
def baixar_arquivo(url, nome_arquivo):
    try:
        resposta = requests.get(url, timeout=10)
        resposta.raise_for_status()

        with open(nome_arquivo, "wb") as arquivo:
            arquivo.write(resposta.content)

        print(f"Download realizado com sucesso: {nome_arquivo}")

    except requests.exceptions.RequestException as erro:
        print(f"Erro ao realizar o download: {erro}")

In [14]:
url = "https://picsum.photos/400/400"

baixar_arquivo(url, "imagem.jpg")

Download realizado com sucesso: imagem.jpg

**Nível 3: Avançado (Webscraping e Ética)**

In [15]:
url_robots = "https://books.toscrape.com/robots.txt"

resposta = requests.get(url_robots, timeout=10)

print(resposta.status_code)
print(resposta.text)

404
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.21.6</center>
</body>
</html>

In [17]:
url = "https://books.toscrape.com/"

resposta = requests.get(url, timeout=10)
resposta.raise_for_status()

soup = BeautifulSoup(resposta.text, "html.parser")

In [18]:
livros = soup.select("article.product_pod")[:5]

dados_livros = []

for livro in livros:
    titulo = livro.h3.a["title"]
    preco = livro.select_one(".price_color").text

    dados_livros.append({
        "titulo": titulo,
        "preco": preco
    })

dados_livros

[{'titulo': 'A Light in the Attic', 'preco': 'Â£51.77'},
 {'titulo': 'Tipping the Velvet', 'preco': 'Â£53.74'},
 {'titulo': 'Soumission', 'preco': 'Â£50.10'},
 {'titulo': 'Sharp Objects', 'preco': 'Â£47.82'},
 {'titulo': 'Sapiens: A Brief History of Humankind', 'preco': 'Â£54.23'}]

In [21]:
df_livros = pd.DataFrame(dados_livros)

df_livros.to_csv("livros.csv", index=False)

print("Arquivo livros.csv salvo com sucesso!")

Arquivo livros.csv salvo com sucesso!

In [24]:
url = "https://pt.wikipedia.org/wiki/Liga_dos_Campe%C3%B5es_da_UEFA"

pagina = requests.get(
    url,
    headers={'User-Agent': 'Mozilla/5.0'},
    timeout=20
)

print("Página baixada — status", pagina.status_code)

Página baixada — status 200

In [26]:
tabelas = pd.read_html(io.StringIO(pagina.text))

print("Quantidade de tabelas:", len(tabelas))

for i, tabela in enumerate(tabelas):
    print(f"\n--- Tabela {i} ---")
    print(tabela.head())

Quantidade de tabelas: 23

--- Tabela 0 ---
                                                   0  \
0  Temporada, competição ou edição atual:  Liga d...
1                                                NaN
2                                       Outros nomes
3                                      Anteriormente
4                                        Organização

                                                   1
0  Temporada, competição ou edição atual:  Liga d...
1                                                NaN
2  UEFA Champions League (em inglês) e Liga dos C...
3  Taça dos Clubes Campeões Europeus Taça da Euro...
4                                               UEFA

--- Tabela 1 ---
                             Unnamed: 0                            Unnamed: 1  \
0  Primeira qualificatória (32 equipes)  Primeira qualificatória (32 equipes)
1                Segunda qualificatória     Caminho dos Campeões (24 equipes)
2                Segunda qualificatória           Caminho da Liga (6 equipes)
3               Terceira qualificatória     Caminho dos Campeões (12 equipes)
4               Terceira qualificatória           Caminho da Liga (8 equipes)

                     Equipes que entram nesta rodada  \
0  33 campeões das associações 23–55 (exceto Liec...
1                   8 campeões das associações 15–22
2           6 segundo colocados de associações 10–15
3                                                NaN
4  3 segundo colocados das associações 7–9 1 terc...

              Equipes que avançam da rodada anterior
0                                                NaN
1           16 vencedores da primeira qualificatória
2                                                NaN
3  12 vencedores da segunda qualificatória (Camin...
4  3 vencedores da segunda qualificatória (Caminh...

--- Tabela 2 ---
               Campeões da Liga dos Campeões da UEFA         Unnamed: 1  \
0  Ano Sede Final Semifinalistas[nota 1] Campeão ...                NaN
1                                                Ano               Sede
2                                                Ano               Sede
3                                   1955–56 Detalhes   Parc des Princes
4                                   1956–57 Detalhes  Santiago Bernabéu

    Unnamed: 2  Unnamed: 3    Unnamed: 4              Unnamed: 5  \
0          NaN         NaN           NaN                     NaN
1        Final       Final         Final  Semifinalistas[nota 1]
2      Campeão  Placar(es)  Vice-campeão  Semifinalistas[nota 1]
3  Real Madrid       4 – 3   Stade Reims                   Milan
4  Real Madrid       2 – 0    Fiorentina       Manchester United

               Unnamed: 6 Unnamed: 7 Unnamed: 8
0                     NaN        NaN        NaN
1  Semifinalistas[nota 1]        NaN        NaN
2  Semifinalistas[nota 1]        NaN        NaN
3               Hibernian        NaN        NaN
4        Estrela Vermelha        NaN        NaN

--- Tabela 3 ---
                Ano               Sede        Final               \
                Ano               Sede      Campeão   Placar(es)
0  1955–56 Detalhes   Parc des Princes  Real Madrid        4 – 3
1  1956–57 Detalhes  Santiago Bernabéu  Real Madrid        2 – 0
2  1957–58 Detalhes             Heysel  Real Madrid  3 – 2 (pro)
3  1958–59 Detalhes      Neckarstadion  Real Madrid        2 – 0
4  1959–60 Detalhes       Hampden Park  Real Madrid        7 – 3

                       Semifinalistas[nota 1]                           \
          Vice-campeão Semifinalistas[nota 1] Semifinalistas[nota 1].1
0          Stade Reims                  Milan                Hibernian
1           Fiorentina      Manchester United         Estrela Vermelha
2                Milan                  Vasas        Manchester United
3          Stade Reims     Atlético de Madrid               Young Boys
4  Eintracht Frankfurt              Barcelona                  Rangers

  Unnamed: 7_level_0 Unnamed: 8_level_0
  Unnamed: 7_level_1 Unnamed: 8_level_1
0                NaN                NaN
1                NaN                NaN
2                NaN                NaN
3                NaN                NaN
4                NaN                NaN

--- Tabela 4 ---
              Clubes                                            Títulos  \
0        Real Madrid  15 (1955–56, 1956–57, 1957–58, 1958–59, 1959–6...
1              Milan  7 (1962–63, 1968–69, 1988–89, 1989–90, 1993–94...
2  Bayern de Munique  6 (1973–74, 1974–75, 1975–76, 2000–01, 2012–13...
3          Liverpool  6 (1976–77, 1977–78, 1980–81, 1983–84, 2004–05...
4          Barcelona   5 (1991–92, 2005–06, 2008–09, 2010–11 e 2014–15)

                                              Vices
0                    3 (1961–62, 1963–64 e 1980–81)
1           4 (1957–58, 1992–93, 1994–95 e 2004–05)
2  5 (1981–82, 1986–87, 1998–99, 2009–10 e 2011–12)
3           4 (1984–85, 2006–07, 2017–18 e 2021–22)
4                    3 (1960–61, 1985–86 e 1993–94)

--- Tabela 5 ---
            País  Títulos  Vices  Participações  Clube(s) Campeões  Aprov.
0        Espanha       20     11             31                  2  64,51%
1     Inglaterra       15     12             27                  6   55,5%
2         Itália       12     18             30                  3     40%
3       Alemanha        8     11             19                  3  42,10%
4  Países Baixos        6      2              8                  3     75%

--- Tabela 6 ---
         País  Finais                                            Cidades
0      Itália       9                      Milão (4), Roma (4), Bari (1)
1  Inglaterra       9                        Londres (8), Manchester (1)
2    Alemanha       9  Munique (5), Stuttgart (2), Gelsenkirchen (1),...
3     Espanha       9             Madrid (6), Barcelona (2), Sevilha (1)
4      França       6                         Paris (3), Saint-Denis (3)

--- Tabela 7 ---
                Estádio  Finais  \
0    Estádio de Wembley       8
1              San Siro       4
2     Santiago Bernabéu       4
3  Estádio Rei Balduíno       4
4         Praterstadion       4

                                                Anos
0  1962–63, 1967–68, 1970–71, 1977–78, 1991–92, 2...
1                 1964–65, 1969–70, 2000–01, 2015–16
2                 1956–57, 1968–69, 1979–80, 2009–10
3                 1957–58, 1965–66, 1973–74, 1984–85
4                 1963–64, 1986–87, 1989–90, 1994–95

--- Tabela 8 ---
             Jogador       País  Jogos  \
0  Cristiano Ronaldo   Portugal    183
1      Iker Casillas    Espanha    177
2       Lionel Messi  Argentina    163
3      Thomas Müller   Alemanha    163
4      Karim Benzema     França    152

                                            Clube(s)
0  Manchester United (59)  Real Madrid (101)  Juv...
1                      Real Madrid (150)  Porto (27)
2           Barcelona (149) Paris Saint-Germain (14)
3                            Bayern de Munique (163)
4                       Lyon (19)  Real Madrid (133)

--- Tabela 9 ---
              Jogador       País  Gols  \
0   Cristiano Ronaldo   Portugal   141
1        Lionel Messi  Argentina   129
2  Robert Lewandowski    Polónia   105
3       Karim Benzema     França    90
4       Raúl González    Espanha    71

                                          Clube(s)
0         Manchester United, Real Madrid, Juventus
1                   Barcelona, Paris Saint-Germain
2  Borussia Dortmund, Bayern de Munique, Barcelona
3                                Lyon, Real Madrid
4                          Real Madrid, Schalke 04

--- Tabela 10 ---
             Jogador       País  Edições                        Clube(s)
0  Cristiano Ronaldo   Portugal        7  Manchester United, Real Madrid
1       Lionel Messi  Argentina        6                       Barcelona
2        Gerd Müller   Alemanha        4               Bayern de Munique

--- Tabela 11 ---
             Jogador       País  Edições  \
0  Cristiano Ronaldo   Portugal       42
1     Ángel Di Maria  Argentina       41
2       Lionel Messi  Argentina       40

                                    Clube(s)
0             Manchester United, Real Madrid
1  Real Madrid  Paris Saint-Germain  Benfica
2                                  Barcelona

--- Tabela 12 ---
           Jogador  Títulos                                    Anos que venceu
0  Francisco Gento        6  1955–56, 1956–57, 1957–58, 1958–59, 1959–60, 1...
1       Toni Kroos        6  2012–13, 2015–16, 2016–17, 2017–18, 2021–22, 2...
2      Luka Modrić        6  2013–14, 2015–16, 2016–17, 2017–18, 2021–22, 2...
3  Daniel Carvajal        6  2013–14, 2015–16, 2016–17, 2017–18, 2021–22, 2...
4  Nacho Fernández        6  2013–14, 2015–16, 2016–17, 2017–18, 2021–22, 2...

--- Tabela 13 ---
         Treinador  Títulos                              Anos que venceu
0  Carlo Ancelotti        5  2002–03, 2006–07, 2013–14, 2021–22, 2023–24
1      Bob Paisley        3                    1976–77, 1977–78, 1980–81
2  Josep Guardiola        3                    2008–09, 2010–11, 2022–23
3  Zinédine Zidane        3                    2015–16, 2016–17, 2017–18
4     Luis Enrique        3                    2014–15, 2024–25, 2025–26

--- Tabela 14 ---
                              Recorde  \
0                        Mais troféus
1                      Maior goleador
2                    Maior assistente
3  Mais participações diretas em gols
4        Maior artilheiro por edições

                                             Jogador    Score  \
0  Francisco Gento, Nacho Fernández, Luka Modrić,...        6
1                                  Cristiano Ronaldo  141[61]
2                                  Cristiano Ronaldo   42[61]
3                                  Cristiano Ronaldo      183
4                                  Cristiano Ronaldo        7

                                   Clube(s)
0            Real Madrid, Bayern de Munique
1  Manchester United, Real Madrid, Juventus
2  Manchester United, Real Madrid, Juventus
3  Manchester United, Real Madrid, Juventus
4            Manchester United, Real Madrid

--- Tabela 15 ---
            Jogador           Posição  \
0     Ronald Koeman          Zagueiro
1   Dejan Savićević     Meio-atacante
2   Marcel Desailly          Zagueiro
3    Frank Rijkaard  Zagueiro/Volante
4  Vladimir Jugović     Meio-campista

                                            Clube(s)
0      PSV Eindhoven (1987–88) e Barcelona (1991–92)
1       Estrela Vermelha (1990–91) e Milan (1993–94)
2  Olympique de Marseille (1992–93) e Milan (1993...
3         Milan (1988–89 e 1989–90) e Ajax (1994–95)
4    Estrela Vermelha (1990–91) e Juventus (1995–96)

--- Tabela 16 ---
   Aparições            Jogador                                     Clube
0         15  Cristiano Ronaldo  Manchester United, Real Madrid, Juventus
1         12              Messi            Barcelona, Paris Saint-Germain
2          9       Sérgio Ramos                               Real Madrid

--- Tabela 17 ---
    Ano            Jogador       Posição  \
0  2024  Cristiano Ronaldo  Centroavante

                                      Clube
0  Manchester United, Real Madrid, Juventus

--- Tabela 18 ---
                                       Jogadores  \
0                                  Kylian Mbappé
1                                Kevin De Bruyne
2                                Vinícius Júnior
3  Antoine Griezmann Jude Bellingham Rafael Leão
4                               Lautaro Martinez

                                  Clube  Prêmios
0                           Real Madrid       12
1                                Napoli       10
2                           Real Madrid        9
3  Atletico de Madrid Real Madrid Milan        8
4                        Inter de Milão        7

--- Tabela 19 ---
  Temporada                Jogador         Posição                Clube
0   2021–22          Karim Benzema    Centroavante          Real Madrid
1   2022–23                  Rodri         Volante      Manchester City
2   2023–24        Vinícius Júnior  Ponta-esquerda          Real Madrid
3   2024–25        Ousmane Dembélé   Ponta-direita  Paris Saint-Germain
4   2025-26  Khvicha Kvaratskhelia        Atacante  Paris Saint-Germain

--- Tabela 20 ---
  vdeLiga dos Campeões da UEFA  \
0                    Masculino
1                      Edições
2                       Finais
3                     Feminino
4                       Sub-19

                      vdeLiga dos Campeões da UEFA.1
0  Edições 1955–56 1956–57 1957–58 1958–59 1959–6...
1  1955–56 1956–57 1957–58 1958–59 1959–60 1960–6...
2  1955–56 1956–57 1957–58 1958–59 1959–60 1960–6...
3  2001–02 2002–03 2003–04 2004–05 2005–06 2006–0...
4  2013–14 2014–15 2015–16 2016–17 2017–18 2018–1...

--- Tabela 21 ---
         0                                                  1
0  Edições  1955–56 1956–57 1957–58 1958–59 1959–60 1960–6...
1   Finais  1955–56 1956–57 1957–58 1958–59 1959–60 1960–6...

--- Tabela 22 ---
                        0                                                  1
0  Controle de autoridade  : Q18756  WorldCat VIAF: 126570080 BNE: XX5367...

In [28]:
df = tabelas[9]
df.head()

,Jogador,País,Gols,Clube(s)
0,Cristiano Ronaldo,Portugal,141,"Manchester United, Real Madrid, Juventus"
1,Lionel Messi,Argentina,129,"Barcelona, Paris Saint-Germain"
2,Robert Lewandowski,Polónia,105,"Borussia Dortmund, Bayern de Munique, Barcelona"
3,Karim Benzema,França,90,"Lyon, Real Madrid"
4,Raúl González,Espanha,71,"Real Madrid, Schalke 04"